// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    return $('dt').click(function(e) {
      var add_class, son;
      son = $(e.currentTarget).next('dd');
      add_class = true;
      if (son.hasClass("expanded")) {
        add_class = false;
      }
      $("dd.expanded").removeClass("expanded");
      if (add_class) {
        return son.addClass("expanded");
      }
    });
  });

}).call(this);
